
```{r}
df = subset(merged_data, select = -c(TEAM, G, W, POSTSEASON, SEED, YEAR, UNITID, STREET, CITY, STATE, ZIP, STFIP, NMCNTY, LOCALE, LAT, LON, CBSA, NMCBSA, CBSATYPE, CSA, NMCSA, NMNECTA, CD, SLDL, SLDU, SCHOOLYEAR, CNTY, NECTA))
df$Conference <- gsub("ind", "Ind", df$Conference)
write.csv(df, "conference_stats.csv", row.names=FALSE)
conf_stats <- read.csv("conference_stats.csv")
```



```{r}
library(shiny)
library(tidyverse)
library(leaflet)
library(ggplot2)
library(dplyr)

merged_data <- left_join(bb_data, college_geo, by = "TEAM")
colnames(merged_data)[2] <- "TEAM"
colnames(merged_data)[2] <- "Conference"
colnames(merged_data)[5] <- "Adjusted Offensive Efficiency"
colnames(merged_data)[6] <- "Adjusted Defensive Efficiency"
colnames(merged_data)[7] <- "Power Rating"
colnames(merged_data)[8] <- "Effective Field Goal Percentage Shot"
colnames(merged_data)[9] <- "Effective Field Goal Percentage Allowed"
colnames(merged_data)[10] <- "Turnover Percentage"
colnames(merged_data)[11] <- "Steal Rate"
colnames(merged_data)[12] <- "Offensive Rebound Rate"
colnames(merged_data)[13] <- "Offensive Rebound Rate Allowed"
colnames(merged_data)[14] <- "Free Throw Rate"
colnames(merged_data)[15] <- "Free Throw Rate Allowed"
colnames(merged_data)[16] <- "Two Point Shooting Range"
colnames(merged_data)[17] <- "Two Point Shooting Range Allowed"
colnames(merged_data)[18] <- "Three Point Shooting Range"
colnames(merged_data)[19] <- "Three Point Shooting Range Allowed"
colnames(merged_data)[20] <- "Adjusted Tempo"
colnames(merged_data)[21] <- "Wins Above Bubble"
df = subset(merged_data, select = -c(TEAM, G, W, POSTSEASON, SEED, YEAR, UNITID, STREET, CITY, STATE, ZIP, STFIP, NMCNTY, LOCALE, LAT, LON, CBSA, NMCBSA, CBSATYPE, CSA, NMCSA, NMNECTA, CD, SLDL, SLDU, SCHOOLYEAR, CNTY, NECTA))
df$Conference <- gsub("ind", "Ind", df$Conference)

write.csv(df, "conference_stats.csv", row.names=FALSE)

conf_stats <- read.csv("conference_stats.csv")

colnames(conf_stats) <- gsub("\\.", " ", colnames(conf_stats))

# df <- select(merged_data, 
```

```{r}
conf_stats <- read.csv("conference_stats.csv")
```

```{r}

d3heatmap(log1p(conf_avg), scale = "column", Rowv = row_labels, dendrogram = "none", colors = "Blues", )

```
```{r}
# 
class(conf_heatmapdata)

```
```{r}
conf_heatmapdata <- read.csv("conference_stats.csv")
heatmap_data <- as.matrix(conf_heatmapdata[, -1])
row_labels <- conf_heatmapdata$Conference

# Create the heatmap
d3heatmap(heatmap_data, scale = "column", Rowv = row_labels, dendrogram = "none", colors = "Blues")
```
```{r}
conf_avg <- read.csv("conference_statsAVG.csv")
summary(conf_avg)
```
```{r}
dput(head(conf_avg))
```
```{r}
df = subset(merged_data, select = -c(TEAM, G, W, POSTSEASON, SEED, UNITID, STREET, CITY, STATE, ZIP, STFIP, NMCNTY, LOCALE, LAT, LON, CBSA, NMCBSA, CBSATYPE, CSA, NMCSA, NMNECTA, CD, SLDL, SLDU, SCHOOLYEAR, CNTY, NECTA))

write.csv(df,"heatmap_data.csv", row.names=FALSE)

heatmap_stats <- read.csv("heatmap_data.csv")



```
```{r}
set.seed(123)
years <- rep(2013:2023, each = 34)
conferences <- rep(c("A1O", "ACC", "AE", "Amer", "ASun", "B10","B12", "BE", "BSky", "BSth","BW", "CAA", "CUSA", "GWC", "Horz", "ind", "Ivy", "MAAC", "MAC", "MEAC", "MVC", "MWC", "NEC", "OVC", "P12", "Pat", "SB", "SC", "SEC", "Slnd", "Sum", "SWAC", "WAC", "WCC"), times = 10)
variables <- matrix(rnorm(18*10), nrow= 10)
variables[sample(length(variables), 50)] <- NA
heatmap_stats <- data.frame(Year = rep(years, times = 34),
                            Conference = rep(conferences, each = 35) conferences,as.data.frame(variables))
```

```{r}
library(d3heatmap)
d3heatmap(as.matrix(heatmap_stats))
```
```{r}
heatmap_matrix <- as.matrix(heatmap_stats)
```
```{r}
row.names(heatmap_stats) <- heatmap_stats$Conference
```


```{r}
df <- heatmap_stats %>%
  filter(YEAR == input$YEAR)

row.names(df) <- df$Conference


d3heatmap(as.matrix(df))
```


```{r}
df <- heatmap_stats %>%
  filter(YEAR == input$YEAR)

# Check for duplicate row names and handle them
if (anyDuplicated(df$Conference)) {
  # Make row names unique if there are duplicates
  df$Conference <- make.names(df$Conference, unique = TRUE)
}

# Create the heatmap
d3heatmap(as.matrix(df))
```



```{r}
library(dplyr)
selected_year <- c(2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023)
heatmap_stats %>% filter(YEAR == selected_year)
row.names(heatmap_stats) <- heatmap_stats$Conference
heatmap_stats$Conference <- NULL
```
```{r}
row.names(heatmap_stats) <- heatmap_stats$Conference
heatmap_stats$Conference <- NULL
```

```{r}
output$home_img <- renderImage({
    
    list(src = "www/header_img.png",
         width = "800",
         height = 200)
    
  }, deleteFile = F)
  
  output$logo_img <- renderImage({
    
    list(src = "www/logo_img.png",
         width = "450",
         height = 400)
    
  }, deleteFile = F)
  
  
  output$textBox <- renderText({
    "Welcome to our cutting-edge dashboard, where we look at a decades worth of statistical data on NCAA Division 1 basketball teams. The postseason
    period of college basketball, coined March Madness, is one of the most revered sporting events of all time. Statistical data covers both in-season and post-season information, including importatn points such as power ranking, win percentage,
    period of college basketball, coined 'March Madness'', is one of the most revered sporting events of all time. Statistical data covers both in-season and post-season information, including importatn points such as power ranking, win percentage,
    and free throw success. This data illustrates a unique narrative about each season and how the game of basektball has evolved over the 
    last decade. Data can be used to understand conference performance, recruitment patterns, the impact of rule changes and adaptations, 
    and team trends over time. This app provides a comprehensive understanding of the sport's development over time by identifying patterns and
    trends useful for anyone who appreciates the sport. Important to note, however, is the COVID-19 pandemic that occurred; there is not data from the year 2020,
    because postseason college basketbakll games were not held."
  })
  
```
```{r}

```

```{r}
df2 <- data.frame(cbind(names(df), t(df)))
colnames(df2) <- c('Variables')

```
```{r}
all_years <- df
filter(all_years) %>%
  select(Conference)

row.names(all_years) <- all_years$Conference

```
```{r}
library(dplyr)
 all_years <- filter(df, input == YEAR)
```



```