---
title: "creating data frame"
author: "Sophia"
date: "10/30/2023"
output: html_document
---

```{r}
geodf <- read.csv("geodata.csv")
colnames(geodf)[2] <- "TEAM"
write.csv(geodf, "geodata.csv", row.names=FALSE)

college_geo <- read.csv("geodata.csv")
bb_data <- read.csv("cbb.csv")

library(dplyr)
merged_data <- left_join(bb_data, college_geo, by = "TEAM")

library(leaflet)
leaflet(data = merged_data) %>% setView(lng = -95.71, lat = 37.09, zoom =3) %>% 
  addTiles() %>%
  addCircleMarkers(radius = 1, label = ~TEAM)
```

```{r}
#Conference Tab:

#Output for Bar Graphs  
output$BarGraphs <- renderTable(
  
)
```


```{r}
merged_data %>%
  group_by(TEAM) %>%
  summarize(Count = sum(POSTSEASON == "Champions", na.rm = TRUE)) %>%
  filter(Count>0)

```


```{r}
merged_data %>%
  group_by(TEAM) %>%
  summarize(Count = sum(SEED <= 4, na.rm = FALSE))  %>%
  filter(Count>0)
```


```{r}
merged_data %>%
  group_by(TEAM) %>%
  summarize(Count = sum(POSTSEASON == "2ND", na.rm = TRUE)) %>%
  filter(Count>0)
```

```{r}
merged_data %>%
  group_by(TEAM) %>%
  summarize(Count = sum(POSTSEASON == "E8", na.rm = TRUE)) %>%
  filter(Count>0)
```

```{r}
merged_data %>%
  group_by(TEAM) %>%
  summarize(Count = sum(POSTSEASON == "F4", na.rm = TRUE)) %>%
  filter(Count>0)
```

```{r}
merged_data %>%
  group_by(TEAM) %>%
  summarize(Count = sum(POSTSEASON == "S16", na.rm = TRUE)) %>%
  filter(Count>0)
```


```{r}
merged_data %>%
  group_by(TEAM) %>%
  summarize(AvgValue = mean(FTR))
```

```{r}
library(ggplot2)
library(tidyverse)
ggplot(merged_data, aes(CONF, FTR)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(angle = 60, hjust  = 1))
```

```{r}
library(ggplot2)

ggplot(data = merged_data, aes(x = factor(CONF), y = factor(YEAR), fill = FTR)) + 
  geom_tile() + 
  scale_fill_gradient(low = "white", high = "blue") +
  labs(title = "Heatmap of Conference Winner Free Throws", x = "CONF", y = "POSTSEAON") +
  theme_minimal()
```
```{r}
library(leaflet)
library(sf)
library(leaflet.extras)

us_map <- leaflet() %>%
  setView(lng = -96, lat = 37.8, zoom = 4) %>%
  addProviderTiles("CartoDB.Positron")

us_map <- us_map %>%
  addHeatmap( data = merged_data, radius = 2)

View(us_map)
```

```{r}
library(tidyverse)
ggplot(merged_data, aes(CONF, ADJOE)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(angle = 60, hjust  = 1))
```

```{r}
library(ggplot2)
library(tidyverse)
ggplot(merged_data, aes(CONF, ADJDE)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(angle = 60, hjust  = 1))
```

```{r}
ggplot(merged_data, aes(STATE, W)) + geom_bar(stat = 'identity') + theme(axis.text.x = element_text(angle = 60, hjust  = 1))
```

```{r}

library(leaflet)
library(geojsonio)
library(tidyverse)
library(sf)
library(dplyr)
library(ggplot2)

state_names_data <- read.csv("table-data.csv")
merged_data <- merged_data  %>%
  left_join(state_names_data, by = c("STATE" = "code"))

state_avgPR <- merged_data %>%
  group_by(state.x) %>%
  summarize(avgPR = mean(BARTHAG), na.rm = TRUE)

geo <- geojson_read("states.geo.json", what = "sp")

geo@data <- left_join(geo@data, state_avgPR, by = c("NAME" ="state.x"))

pal <- colorBin("Blues", domain = geo@data$BARTHAG)
```

```{r}

leaflet(geo) %>%
  addPolygons(fillOpacity = 2.5,
              fillColor = ~pal(avgPR),
              color = "white",
              dashArray = '3',
              weight = 03)

```

```{r}

state_FTHROW <- merged_data %>%
  group_by(state.x) %>%
  summarize(avgFT = mean(EFG_O), na.rm = TRUE)

geo <- geojson_read("states.geo.json", what = "sp")

geo@data <- left_join(geo@data, state_FTHROW, by = c("NAME" ="state.x"))

pal <- colorBin("Blues", domain = geo@data$BARTHAG)
```

```{r}

leaflet(geo) %>%
  addPolygons(fillOpacity = 2.5,
              fillColor = ~pal(avgFT),
              color = "white",
              dashArray = '3',
              weight = 2)

```


```{r}
state_FGOAL <- merged_data %>%
  group_by(state.x) %>%
  summarize(avgFG = mean(EFG_O), na.rm = TRUE)

geo <- geojson_read("states.geo.json", what = "sp")

geo@data <- left_join(geo@data, state_FGOAL, by = c("NAME" ="state.x"))

pal <- colorBin("Blues", domain = geo@data$EFG_O)
```

```{r}

leaflet(geo) %>%
  addPolygons(fillOpacity = 2.5,
              fillColor = ~pal(avgFG),
              color = "white",
              dashArray = '3',
              weight = 2)

```

```{r}

state_turnover <- merged_data %>%
  group_by(state.x) %>%
  summarize(avgTOR = mean(TOR), na.rm = TRUE)

geo <- geojson_read("states.geo.json", what = "sp")

geo@data <- left_join(geo@data, state_turnover, by = c("NAME" ="state.x"))

pal <- colorBin("Blues", domain = geo@data$TOR)
```

```{r}

leaflet(geo) %>%
  addPolygons(fillOpacity = 2.5,
              fillColor = ~pal(avgTOR),
              color = "white",
              dashArray = '3',
              weight = 2)

```


```{r}

state_avgsteal <- merged_data %>%
  group_by(state.x) %>%
  summarize(avgTORD = mean(TORD), na.rm = TRUE)

geo <- geojson_read("states.geo.json", what = "sp")

geo@data <- left_join(geo@data, state_avgsteal, by = c("NAME" ="state.x"))

pal <- colorBin("Blues", domain = geo@data$TORD)
```

```{r}

leaflet(geo) %>%
  addPolygons(fillOpacity = 2.5,
              fillColor = ~pal(avgTORD),
              color = "white",
              dashArray = '3',
              weight = 3)

```


```{r}
state_offRebound <- merged_data %>%
  group_by(state.x) %>%
  summarize(avgORB= mean(ORB), na.rm = TRUE)

geo <- geojson_read("states.geo.json", what = "sp")

geo@data <- left_join(geo@data, state_offRebound, by = c("NAME" ="state.x"))

pal <- colorBin("Blues", domain = geo@data$ORB)
```

```{r}

leaflet(geo) %>%
  addPolygons(fillOpacity = 2.5,
              fillColor = ~pal(avgORB),
              color = "white",
              dashArray = '3',
              weight = 3)

```


```{r}
state_avgFTR <- merged_data %>%
  group_by(state.x) %>%
  summarize(avgFTR= mean(FTR), na.rm = TRUE)

geo <- geojson_read("states.geo.json", what = "sp")

geo@data <- left_join(geo@data, state_avgFTR, by = c("NAME" ="state.x"))

pal <- colorBin("Blues", domain = geo@data$FTR)
```

```{r}

leaflet(geo) %>%
  addPolygons(fillOpacity = 2.5,
              fillColor = ~pal(avgFTR),
              color = "white",
              dashArray = '3',
              weight = 3)

```



```{r}
state_avgTempo <- merged_data %>%
  group_by(state.x) %>%
  summarize(avgTEMPO= mean(ADJ_T), na.rm = TRUE)

geo <- geojson_read("states.geo.json", what = "sp")

geo@data <- left_join(geo@data, state_avgTempo, by = c("NAME" ="state.x"))

pal <- colorBin("Blues", domain = geo@data$ADJ_T)
```

```{r}

leaflet(geo) %>%
  addPolygons(fillOpacity = 1,
              fillColor = ~pal(avgTEMPO),
              color = "white",
              dashArray = '3',
              weight = 4)

```




